//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace PertentoBI.BusinessObjects.Database
{

    [Persistent(@"PBI_Categories")]
    public partial class Categories : XPLiteObject
    {
        int fCategoryID;
        [Key(true)]
        public int CategoryID
        {
            get { return fCategoryID; }
            set { SetPropertyValue<int>(nameof(CategoryID), ref fCategoryID, value); }
        }
        string fCode;
        [Size(50)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fLeftValue;
        public int LeftValue
        {
            get { return fLeftValue; }
            set { SetPropertyValue<int>(nameof(LeftValue), ref fLeftValue, value); }
        }
        int fRightValue;
        public int RightValue
        {
            get { return fRightValue; }
            set { SetPropertyValue<int>(nameof(RightValue), ref fRightValue, value); }
        }
        int fParentID;
        public int ParentID
        {
            get { return fParentID; }
            set { SetPropertyValue<int>(nameof(ParentID), ref fParentID, value); }
        }
        int fTreeID;
        public int TreeID
        {
            get { return fTreeID; }
            set { SetPropertyValue<int>(nameof(TreeID), ref fTreeID, value); }
        }
        bool fIsContainerOnly;
        public bool IsContainerOnly
        {
            get { return fIsContainerOnly; }
            set { SetPropertyValue<bool>(nameof(IsContainerOnly), ref fIsContainerOnly, value); }
        }
        bool fIsSingleSelectionTree;
        public bool IsSingleSelectionTree
        {
            get { return fIsSingleSelectionTree; }
            set { SetPropertyValue<bool>(nameof(IsSingleSelectionTree), ref fIsSingleSelectionTree, value); }
        }
        bool fIsSearchable;
        [ColumnDbDefaultValue("((0))")]
        public bool IsSearchable
        {
            get { return fIsSearchable; }
            set { SetPropertyValue<bool>(nameof(IsSearchable), ref fIsSearchable, value); }
        }
        bool fIsSubscriptionBased;
        [ColumnDbDefaultValue("((0))")]
        public bool IsSubscriptionBased
        {
            get { return fIsSubscriptionBased; }
            set { SetPropertyValue<bool>(nameof(IsSubscriptionBased), ref fIsSubscriptionBased, value); }
        }
        bool fDeleted;
        [ColumnDbDefaultValue("((0))")]
        public bool Deleted
        {
            get { return fDeleted; }
            set { SetPropertyValue<bool>(nameof(Deleted), ref fDeleted, value); }
        }
        string fWField1;
        [Size(255)]
        public string WField1
        {
            get { return fWField1; }
            set { SetPropertyValue<string>(nameof(WField1), ref fWField1, value); }
        }
        string fWField2;
        [Size(255)]
        public string WField2
        {
            get { return fWField2; }
            set { SetPropertyValue<string>(nameof(WField2), ref fWField2, value); }
        }
        string fWField3;
        [Size(255)]
        public string WField3
        {
            get { return fWField3; }
            set { SetPropertyValue<string>(nameof(WField3), ref fWField3, value); }
        }
        string fWField4;
        [Size(255)]
        public string WField4
        {
            get { return fWField4; }
            set { SetPropertyValue<string>(nameof(WField4), ref fWField4, value); }
        }
        string fWField5;
        [Size(255)]
        public string WField5
        {
            get { return fWField5; }
            set { SetPropertyValue<string>(nameof(WField5), ref fWField5, value); }
        }
        string fType;
        [Size(20)]
        public string Type
        {
            get { return fType; }
            set { SetPropertyValue<string>(nameof(Type), ref fType, value); }
        }
        DateTime fCreatedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDate), ref fCreatedDate, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        DateTime fUpdatedDate;
        public DateTime UpdatedDate
        {
            get { return fUpdatedDate; }
            set { SetPropertyValue<DateTime>(nameof(UpdatedDate), ref fUpdatedDate, value); }
        }
        int fUpdatedBy;
        public int UpdatedBy
        {
            get { return fUpdatedBy; }
            set { SetPropertyValue<int>(nameof(UpdatedBy), ref fUpdatedBy, value); }
        }
        [Association(@"DatasourceCategoriesReferencesCategories")]
        public XPCollection<DatasourceCategories> DatasourceCategoriesCollection { get { return GetCollection<DatasourceCategories>(nameof(DatasourceCategoriesCollection)); } }
    }

}
