//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace PertentoBI.BusinessObjects.Database
{

    [Persistent(@"PBI_DashboardDatasources")]
    public partial class DashboardDatasources : XPLiteObject
    {
        int fDashboardDatasourceID;
        [Key(true)]
        public int DashboardDatasourceID
        {
            get { return fDashboardDatasourceID; }
            set { SetPropertyValue<int>(nameof(DashboardDatasourceID), ref fDashboardDatasourceID, value); }
        }
        DataSources fDatasourceID;
        [Association(@"DashboardDatasourcesReferencesDataSources")]
        public DataSources DatasourceID
        {
            get { return fDatasourceID; }
            set { SetPropertyValue<DataSources>(nameof(DatasourceID), ref fDatasourceID, value); }
        }
        Dashboards fDashboardID;
        [Association(@"DashboardDatasourcesReferencesDashboards")]
        public Dashboards DashboardID
        {
            get { return fDashboardID; }
            set { SetPropertyValue<Dashboards>(nameof(DashboardID), ref fDashboardID, value); }
        }
        DateTime fCreatedDate;
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDate), ref fCreatedDate, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        DateTime fUpdatedDate;
        public DateTime UpdatedDate
        {
            get { return fUpdatedDate; }
            set { SetPropertyValue<DateTime>(nameof(UpdatedDate), ref fUpdatedDate, value); }
        }
        int fUpdatedBy;
        public int UpdatedBy
        {
            get { return fUpdatedBy; }
            set { SetPropertyValue<int>(nameof(UpdatedBy), ref fUpdatedBy, value); }
        }
    }

}
