//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace PertentoBI.BusinessObjects.Database
{

    [Persistent(@"PBI_DataSources")]
    public partial class DataSources : XPLiteObject
    {
        int fDataSourceID;
        [Key(true)]
        public int DataSourceID
        {
            get { return fDataSourceID; }
            set { SetPropertyValue<int>(nameof(DataSourceID), ref fDataSourceID, value); }
        }
        string fName;
        [Size(64)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(1024)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fConnectionString;
        [Size(1024)]
        public string ConnectionString
        {
            get { return fConnectionString; }
            set { SetPropertyValue<string>(nameof(ConnectionString), ref fConnectionString, value); }
        }
        string fDbSchema;
        [Size(SizeAttribute.Unlimited)]
        public string DbSchema
        {
            get { return fDbSchema; }
            set { SetPropertyValue<string>(nameof(DbSchema), ref fDbSchema, value); }
        }
        string fProvider;
        public string Provider
        {
            get { return fProvider; }
            set { SetPropertyValue<string>(nameof(Provider), ref fProvider, value); }
        }
        double fCommandTimeout;
        public double CommandTimeout
        {
            get { return fCommandTimeout; }
            set { SetPropertyValue<double>(nameof(CommandTimeout), ref fCommandTimeout, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        DateTime fCreatedDate;
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDate), ref fCreatedDate, value); }
        }
        int fUpdatedBy;
        public int UpdatedBy
        {
            get { return fUpdatedBy; }
            set { SetPropertyValue<int>(nameof(UpdatedBy), ref fUpdatedBy, value); }
        }
        DateTime fUpdatedDate;
        public DateTime UpdatedDate
        {
            get { return fUpdatedDate; }
            set { SetPropertyValue<DateTime>(nameof(UpdatedDate), ref fUpdatedDate, value); }
        }
        [Association(@"DashboardDatasourcesReferencesDataSources")]
        public XPCollection<DashboardDatasources> DashboardDatasourcesCollection { get { return GetCollection<DashboardDatasources>(nameof(DashboardDatasourcesCollection)); } }
        [Association(@"DatasourceCategoriesReferencesDataSources")]
        public XPCollection<DatasourceCategories> DatasourceCategoriesCollection { get { return GetCollection<DatasourceCategories>(nameof(DatasourceCategoriesCollection)); } }
        [Association(@"ReportDatasourcesReferencesDataSources")]
        public XPCollection<ReportDatasources> ReportDatasourcesCollection { get { return GetCollection<ReportDatasources>(nameof(ReportDatasourcesCollection)); } }
    }

}
