//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace PertentoBI.BusinessObjects.Database
{

    [Persistent(@"PBI_Reports")]
    public partial class Reports : XPLiteObject
    {
        int fReportID;
        [Key(true)]
        public int ReportID
        {
            get { return fReportID; }
            set { SetPropertyValue<int>(nameof(ReportID), ref fReportID, value); }
        }
        string fCode;
        [Size(50)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fLeftValue;
        public int LeftValue
        {
            get { return fLeftValue; }
            set { SetPropertyValue<int>(nameof(LeftValue), ref fLeftValue, value); }
        }
        int fRightValue;
        public int RightValue
        {
            get { return fRightValue; }
            set { SetPropertyValue<int>(nameof(RightValue), ref fRightValue, value); }
        }
        int fParentID;
        public int ParentID
        {
            get { return fParentID; }
            set { SetPropertyValue<int>(nameof(ParentID), ref fParentID, value); }
        }
        int fTreeID;
        public int TreeID
        {
            get { return fTreeID; }
            set { SetPropertyValue<int>(nameof(TreeID), ref fTreeID, value); }
        }
        string fReportName;
        [Size(255)]
        public string ReportName
        {
            get { return fReportName; }
            set { SetPropertyValue<string>(nameof(ReportName), ref fReportName, value); }
        }
        bool fIsContainerOnly;
        public bool IsContainerOnly
        {
            get { return fIsContainerOnly; }
            set { SetPropertyValue<bool>(nameof(IsContainerOnly), ref fIsContainerOnly, value); }
        }
        bool fIsSingleSelectionTree;
        public bool IsSingleSelectionTree
        {
            get { return fIsSingleSelectionTree; }
            set { SetPropertyValue<bool>(nameof(IsSingleSelectionTree), ref fIsSingleSelectionTree, value); }
        }
        bool fIsSearchable;
        [ColumnDbDefaultValue("((0))")]
        public bool IsSearchable
        {
            get { return fIsSearchable; }
            set { SetPropertyValue<bool>(nameof(IsSearchable), ref fIsSearchable, value); }
        }
        string fXMLString;
        [Size(3000)]
        public string XMLString
        {
            get { return fXMLString; }
            set { SetPropertyValue<string>(nameof(XMLString), ref fXMLString, value); }
        }
        bool fIsSubscriptionBased;
        public bool IsSubscriptionBased
        {
            get { return fIsSubscriptionBased; }
            set { SetPropertyValue<bool>(nameof(IsSubscriptionBased), ref fIsSubscriptionBased, value); }
        }
        string fReportActionsXML;
        [Size(3000)]
        public string ReportActionsXML
        {
            get { return fReportActionsXML; }
            set { SetPropertyValue<string>(nameof(ReportActionsXML), ref fReportActionsXML, value); }
        }
        string fReportData;
        [Size(SizeAttribute.Unlimited)]
        public string ReportData
        {
            get { return fReportData; }
            set { SetPropertyValue<string>(nameof(ReportData), ref fReportData, value); }
        }
        bool fIsEditable;
        public bool IsEditable
        {
            get { return fIsEditable; }
            set { SetPropertyValue<bool>(nameof(IsEditable), ref fIsEditable, value); }
        }
        bool fHasParameters;
        [ColumnDbDefaultValue("((0))")]
        public bool HasParameters
        {
            get { return fHasParameters; }
            set { SetPropertyValue<bool>(nameof(HasParameters), ref fHasParameters, value); }
        }
        bool fDisplayGroupTree;
        [ColumnDbDefaultValue("((0))")]
        public bool DisplayGroupTree
        {
            get { return fDisplayGroupTree; }
            set { SetPropertyValue<bool>(nameof(DisplayGroupTree), ref fDisplayGroupTree, value); }
        }
        DateTime fCreatedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDate), ref fCreatedDate, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        DateTime fUpdatedDate;
        public DateTime UpdatedDate
        {
            get { return fUpdatedDate; }
            set { SetPropertyValue<DateTime>(nameof(UpdatedDate), ref fUpdatedDate, value); }
        }
        int fUpdatedBy;
        public int UpdatedBy
        {
            get { return fUpdatedBy; }
            set { SetPropertyValue<int>(nameof(UpdatedBy), ref fUpdatedBy, value); }
        }
        [Association(@"ReportDatasourcesReferencesReports")]
        public XPCollection<ReportDatasources> ReportDatasourcesCollection { get { return GetCollection<ReportDatasources>(nameof(ReportDatasourcesCollection)); } }
        [Association(@"UserReportAccessRightsReferencesReports")]
        public XPCollection<UserReportAccessRights> UserReportAccessRightsCollection { get { return GetCollection<UserReportAccessRights>(nameof(UserReportAccessRightsCollection)); } }
    }

}
