//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace PertentoBI.BusinessObjects.Database
{

    [Persistent(@"PBI_UserDatasourceAccessRights")]
    public partial class UserDatasourceAccessRights : XPLiteObject
    {
        int fDatasourceAccessRightID;
        [Key(true)]
        public int DatasourceAccessRightID
        {
            get { return fDatasourceAccessRightID; }
            set { SetPropertyValue<int>(nameof(DatasourceAccessRightID), ref fDatasourceAccessRightID, value); }
        }
        int fDatasourceID;
        public int DatasourceID
        {
            get { return fDatasourceID; }
            set { SetPropertyValue<int>(nameof(DatasourceID), ref fDatasourceID, value); }
        }
        Guid fUsers;
        public Guid Users
        {
            get { return fUsers; }
            set { SetPropertyValue<Guid>(nameof(Users), ref fUsers, value); }
        }
        string fUserType;
        [Size(50)]
        public string UserType
        {
            get { return fUserType; }
            set { SetPropertyValue<string>(nameof(UserType), ref fUserType, value); }
        }
        DateTime fCreatedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime CreatedDate
        {
            get { return fCreatedDate; }
            set { SetPropertyValue<DateTime>(nameof(CreatedDate), ref fCreatedDate, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        DateTime fUpdatedDate;
        public DateTime UpdatedDate
        {
            get { return fUpdatedDate; }
            set { SetPropertyValue<DateTime>(nameof(UpdatedDate), ref fUpdatedDate, value); }
        }
        int fUpdatedBy;
        public int UpdatedBy
        {
            get { return fUpdatedBy; }
            set { SetPropertyValue<int>(nameof(UpdatedBy), ref fUpdatedBy, value); }
        }
    }

}
