'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VehicleUsers
    
    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSurname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartment As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesignation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNationalIDNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNationalIDNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLicenseNumba control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLicenseNumba As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rdExpiryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdExpiryDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdApplicationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdApplicationDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''txtApplicationFormNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtApplicationFormNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboAllocationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAllocationStatus As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''cmdAddNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddNew As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PageLevelTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageLevelTabs As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''lblMultipageLabels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMultipageLabels As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PageLevelMultiPage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageLevelMultiPage1 As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''RadPageViewMedicals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewMedicals As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''rdMedicalsDateIssued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdMedicalsDateIssued As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rdMedicalsExpiryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdMedicalsExpiryDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''cmdSaveMedical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveMedical As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdbtnDeleteMedical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdbtnDeleteMedical As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadPageViewRetests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewRetests As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''radRetestedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radRetestedDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''radRetestedExpiryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radRetestedExpiryDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''cmdSaveRetest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveRetest As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdDeleteRetest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteRetest As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadPageViewDDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewDDC As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''radDateDDCTested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDateDDCTested As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''radDateDDCExpiry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDateDDCExpiry As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''cmdSaveDDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveDDC As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdDeleteDDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteDDC As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''RadPageViewAllocations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageViewAllocations As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''gwList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gwList As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''RadPageView6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView6 As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''RadPageView7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPageView7 As Global.Telerik.Web.UI.RadPageView
End Class
